# Generated by Django 5.1.3 on 2025-01-10 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dollarexchangehistory',
            name='page',
            field=models.CharField(default='https://dolarhoy.com/', max_length=64, verbose_name='Pagina'),
        ),
    ]
