# Generated by Django 5.1.3 on 2025-01-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment_config', '0002_dollarexchangehistory_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dollarexchangehistory',
            name='page',
            field=models.CharField(max_length=64, verbose_name='Pagina'),
        ),
    ]
