# Generated by Django 5.1.3 on 2025-01-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_config', '0005_alter_dollarexchangehistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='key',
        ),
    ]
