# Generated by Django 5.1.3 on 2025-02-16 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment_config', '0006_remove_paymentmethod_key'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentmethod',
            options={'verbose_name': 'Método de pago', 'verbose_name_plural': 'Métodos de pago'},
        ),
    ]
