# Generated by Django 5.1.3 on 2024-11-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=255, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.IntegerField(null=True, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='document',
            field=models.CharField(max_length=15, null=True, unique=True, verbose_name='Documento'),
        ),
    ]
