# Generated by Django 5.1.3 on 2025-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(max_length=15, null=True, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.CharField(max_length=125, verbose_name='Nombre'),
        ),
    ]
