# Generated by Django 5.1.3 on 2025-01-15 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='contact_number',
            field=models.CharField(max_length=16, null=True, verbose_name='Número de contacto'),
        ),
    ]
