services:
  web:
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      -  .:/dparts/
    ports:
      - 8000:8000
    env_file:
      - ./.env.dev
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=repuestostoretto
      - POSTGRES_PASSWORD=repuestostoretto
      - POSTGRES_DB=repuestostoretto
    healthcheck:
      test: "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: