version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "python manage.py collectstatic --noinput &&
        python manage.py migrate &&
        gunicorn app.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - static_volume:/dparts/web/staticfiles
      - media_volume:/dparts/web/media
    expose:
      - 8000
    #env_file:
    #  - ./.env.prod
    depends_on:
      db:
        condition: service_healthy
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/dparts/web/staticfiles
      - media_volume:/dparts/web/media
    ports:
      - 1337:80
    depends_on:
      - web
  db:
    image: postgres:17
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    #env_file:
    #  - ./.env.prod.db
    healthcheck:
      test: "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  static_volume:
  media_volume: