# Generated by Django 5.1.3 on 2024-12-03 19:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Marca'),
        ),
        migrations.AddField(
            model_name='product',
            name='sku',
            field=models.CharField(default=None, max_length=50, null=True, unique=True, verbose_name='SKU'),
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('slug', models.SlugField(unique=True, verbose_name='URL')),
                ('Category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='product.category')),
            ],
            options={
                'verbose_name': 'etiqueta',
                'verbose_name_plural': 'etiquetas',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ProductTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.product', verbose_name='Producto')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tags', to='product.tag', verbose_name='Etiqueta')),
            ],
            options={
                'verbose_name': 'etiqueta de producto',
                'verbose_name_plural': 'etiquetas de productos',
            },
        ),
    ]
