# Generated by Django 5.1.3 on 2025-01-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_tag_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.ManyToManyField(blank=True, through='product.ProductTag', to='product.tag'),
        ),
    ]
