# Generated by Django 5.1.3 on 2025-01-20 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_tag_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hold_stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades en espera'),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades en stock'),
        ),
        migrations.AddField(
            model_name='product',
            name='units_sold',
            field=models.PositiveIntegerField(default=0, verbose_name='Unidades vendidas'),
        ),
    ]
