# Generated by Django 5.1.3 on 2025-01-20 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_product_hold_stock_product_stock_product_units_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hold_stock',
            new_name='stock_on_hold',
        ),
    ]
