# Generated by Django 5.1.3 on 2025-01-20 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_rename_hold_stock_product_stock_on_hold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Precio (USD)'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0, verbose_name='En stock'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock_on_hold',
            field=models.PositiveIntegerField(default=0, verbose_name='En espera'),
        ),
    ]
