# Generated by Django 5.1.3 on 2025-02-19 02:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_product_site'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='site',
        ),
    ]
