# Generated by Django 5.1.3 on 2024-11-13 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0004_alter_product_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('shipping_address', models.TextField(verbose_name='Dirección de Envio')),
                ('contact_number', models.CharField(max_length=11, verbose_name='Número de contacto')),
                ('status', models.CharField(choices=[('PRO', 'En proceso'), ('PAG', 'Pagada'), ('CAN', 'Cancelada'), ('COM', 'Completada')], max_length=3, verbose_name='Estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Monto')),
                ('method_of_payment', models.CharField(choices=[('MOV', 'Pago Movil'), ('TRF', 'Transferencia bancaria')], max_length=3, null=True, verbose_name='Metodo de pago')),
                ('proof_of_payment', models.ImageField(null=True, upload_to='uploads/capturas/', verbose_name='Captura')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'orden',
                'verbose_name_plural': 'ordenes',
                'ordering': ('-created_at', '-updated_at'),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='product.product')),
            ],
            options={
                'verbose_name': 'articulo',
                'verbose_name_plural': 'articulos',
            },
        ),
    ]
