# Generated by Django 5.1.3 on 2024-12-04 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_payment_note'),
        ('product', '0005_product_brand_product_sku_tag_producttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_name',
            field=models.CharField(max_length=100, null=True, verbose_name='Nombre del producto'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='product.product', verbose_name='Producto'),
        ),
    ]
