# Generated by Django 5.1.3 on 2025-01-10 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_order_iva_order_exchange_rate_alter_order_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount_VEF',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Monto (VEF)'),
        ),
    ]
