# Generated by Django 5.1.3 on 2025-01-15 01:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_remove_order_method_of_payment_order_payment_method'),
        ('payment_config', '0005_alter_dollarexchangehistory_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='contact_number',
            field=models.CharField(max_length=16, verbose_name='Número de contacto'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='payment_config.paymentmethod', verbose_name='Cuenta y metodo al que se pago'),
        ),
    ]
