# Generated by Django 5.1.3 on 2025-02-16 01:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (USD)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='amount_VEF',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto (VES)'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PRO', 'En proceso'), ('PAG', 'Pagada'), ('CAN', 'Cancelada'), ('COM', 'Completada'), ('DEL', 'Entregada')], max_length=3, verbose_name='Estado'),
        ),
    ]
